[phases.setup]
  nixPkgs = ["php83", "php83Packages.composer", "nodejs_20"]

[phases.install]
  cmds = ["composer install --no-interaction --optimize-autoloader", "npm install"]

[phases.build]
  cmds = [
    "npm run build",
    "mkdir -p database",
    "touch database/database.sqlite"
  ]

[start]
  # التعديل هنا لضمان استخدام المنفذ الصحيح الموجه من رايلواي
  cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
